/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dummy.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the DummyMessage service. Represents a row in the &quot;dummy_messages_gen&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dummy.model.impl.DummyMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dummy.model.impl.DummyMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DummyMessage
 * @see com.dummy.model.impl.DummyMessageImpl
 * @see com.dummy.model.impl.DummyMessageModelImpl
 * @generated
 */
@ProviderType
public interface DummyMessageModel extends BaseModel<DummyMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dummy message model instance should use the {@link DummyMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this dummy message.
	 *
	 * @return the primary key of this dummy message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dummy message.
	 *
	 * @param primaryKey the primary key of this dummy message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dummy message.
	 *
	 * @return the ID of this dummy message
	 */
	public long getId();

	/**
	 * Sets the ID of this dummy message.
	 *
	 * @param id the ID of this dummy message
	 */
	public void setId(long id);

	/**
	 * Returns the text of this dummy message.
	 *
	 * @return the text of this dummy message
	 */
	@AutoEscape
	public String getText();

	/**
	 * Sets the text of this dummy message.
	 *
	 * @param text the text of this dummy message
	 */
	public void setText(String text);

	/**
	 * Returns the tag of this dummy message.
	 *
	 * @return the tag of this dummy message
	 */
	@AutoEscape
	public String getTag();

	/**
	 * Sets the tag of this dummy message.
	 *
	 * @param tag the tag of this dummy message
	 */
	public void setTag(String tag);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DummyMessage dummyMessage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DummyMessage> toCacheModel();

	@Override
	public DummyMessage toEscapedModel();

	@Override
	public DummyMessage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}